swc-project/swc-node

packages/register/register.ts

Register on Windows will wrongfully skip compilation of files if `CompilerOptions.files` contains absolute paths. Using `path.resolve` instead  of `path.join` makes the check work for both relative and absolute paths.

fix(register): handle absolute file paths

---

README.md

Looks like the benchmark results were updated but this note is still in the readme

Remove note about esbuild being faster

---

packages/register/register.ts

It's very surprising situation, when class names mangles by default.
Example:
I stuck with project, written on **type-graphql** and all types in *schema.graphql* looks like `User1` instead `User`
Maybe better, keepClassNames by default?

register use keepClassNames: true by default

---

packages/jest/index.ts

fixes: @swc-node/jest ignores the config provided with the transformer when using jest@27
https://github.com/facebook/jest/pull/10926 made a breaking change for upcoming jest@27 that renders the current config retrieval non functional. `jestConfig.transform` will be undefined and `jestConfig.transformerConfig` will hold the configuration instead.
See also new `TransformerOptions` type https://github.com/facebook/jest/blob/a28f14a9dbd4621eb2e848034cdfdfec28ff9866/packages/jest-transform/src/types.ts#L63

feat(jest): support jest 27 transformerConfig

---

packages/register/package.json

TypeScript is needed if using pnpm or npm(where the global TypeScript is not installed)
BTW, It's a great project!

fix: make typescript a dependency

---

packages/jest/CHANGELOG.md
packages/jest/package.json
packages/sourcemap-support/CHANGELOG.md
packages/sourcemap-support/package.json

Find these urls are inconsistent (thought works with url redirections). Try to align them with the current repo name.

doc: align repo name urls

---

packages/jest/index.ts

.mjs seems to be the official file extension in node.js for javascript files with es6+ module syntax (instead of commonjs). Allow @swc-node/jest to transpile those. 
e.g. angular with version 13 started to [only ship mjs files](https://github.com/angular/core-builds/blob/master/package.json#L27-L31).

feat: accept to transpile files with .mjs extension

---

README.md

swc-node is GREAT! BUT: I suspect you're losing many potential users because of the README.
Back in January, I wanted something to "run TypeScript with node". I was pointed to swc-node, and I looked at it, but dismissed because it wasn't clear what it did, or how to use it.
Then a few days ago, I was pointed to swc-node again. I looked at it again, and AGAIN I dismissed it because it wasn't clear what it did, or how to use it!
Here are some reasons I failed:
* The top-level README has lots of detail I don't care about. Support matrix right at the top, then detailed benchmarks. Could just say "fast and runs everywhere".
* Small links to sub-project READMEs are called "Detail", but those contain all the useful info! The "detail" is the support matrix and benchmarking.
* The name …

Make it clear how to use swc-node

---

packages/register/register.ts

Currently the `register` method doesn't return the result of `pirates#addHook`, which means you can't revert the registration of the hook. This is very useful in circumstances like `jest-config`, which temporarily registers the transform, reads the config file, then de-registers it. See below
https://github.com/facebook/jest/blob/199f9811ae68b15879cbe18b7ef7ebd61eefcf23/packages/jest-config/src/readConfigFileAndSetRootDir.ts#L83-L101

feat(register): return addHook result to it can be reverted

---

packages/register/register.ts

This adds the opportunity to transpile files within node_modules.
I'm not that familiar with the swc-node library so feel free to close/reimplement as you see fit but decided to leave this PR here to at least share visibility into what we hacked together for our own needs.
```typescript
const { register } = require('@swc-node/register/register')
register(/* use defaults */ undefined, {
ignoreNodeModules: false,
matcher: (filename) => {
// Custom file matcher
return !/node_modules\/(?!@someorg)/.test(filename)
}
}
```
Side note: didn't mean to create this PR here, thought it would go to our own fork of swc-node when I ran `gh pr create` 😆

feat(register): support hook options

---

packages/register/read-default-tsconfig.ts

At the moment, swc-node raise an error if we defined `paths` in `tsconfig.json`
For example: 
```json
{
"compilerOptions": {
"baseUrl": "./src",
"paths": {
"@api/*": ["api/*"]
}
}
}
```
```
Error: Cannot find module '../../../../../api/http-service
```
This pull request is to convert options.paths to absolute paths

fix(register): support paths alias with baseUrl

---

packages/sourcemap-support/package.json
pnpm-lock.yaml

Compiled code of this package requires "tslib" to be installed which is not the case if the porject has "@swc-node/register" as a single dependency.
In that case `npm` will generate the following tree:
```
- node_modules
- @swc-node
- sourcemap-support
- register
- node_modules
- tslib
```
and `tslib` will be insaccessible for "@swc-node/sourcemap-support"

fix(sourcemap-support): add "tslib" as a dependnecy for "sourcemap-suport"

---

packages/sourcemap-support/README.md

`SourcemapMap.set(filename, map)` doesn't do anything unless you've hooked up `installSourceMapSupport` I believe

Fix sourcemap support installation instructions

---

README.md
packages/register/register.ts

This PR adds the ability to load the .swcrc file when running the following command:
```
SWCRC=true node -r @swc-node/register index.ts
```
.swcrc file is needed in some scenarios, and there was no option to load it. For example, when you need to use a plugin, you need to use the following .swcrc file:
```json
{
"jsc": {
"experimental": {
"plugins": [
[
"SWC-plugin-formatjs",
{
"overrideIdFn": "[sha512:contenthash:base64:6]"
}
]
]
}
}
}
```
I have chosen an environment variable because it was the simplest solution with minimal impact. I did not want to cause breaking change, so it is opt-in rather than opt-out. This way, it can be a minor version bump.

Added SWCRC env variable

---

packages/jest/package.json
pnpm-lock.yaml

This simply adds `typescript` as a peer dependency of the **@swc-node/jest** package, effectively passing the peer dependency requirement from **@swc-node/register** onto the consumer of **@swc-node/jest** in order to prevent the following warning:

Pass TypeScript peer dependency to consumer in jest package

---

packages/core/index.ts

Helper functions will show up in jest test coverage as uncovered lines.
I'm opening this PR because it was a quick change to propose, but there may be valid reasons not to do this.
Let me know if you'd like a reproduction of the issue, and happy to discuss further.

Add externalHelpers:true for jest

---

README.md

the `-r` refers to `require` and does not work for esm, should use `--loader` or `--experimental-loader` instead

docs: fix usage example of esm loader

---

packages/core/index.ts
packages/register/__test__/ts-compiler-options-to-swc-config.spec.ts
packages/register/read-default-tsconfig.ts

- respects `experimentalDecorators` and `emitDecoratorMetadata`
- respects SWCRC=true
- adds tests
- fixes #700 #701

Ts Compiler to Swc Config: respects decorators config and SWCRC=true

---

packages/register/register.ts

Fixes #681 
When sourceMap is set to true, the generated map is injected into the code as base-64 inline map, similar to what ts-node/register does

Make sourcemaps work with both error stack & debugger

---

packages/register/esm.mts

like #696 states the `url` returned should return something like: `new URL(url).href`
[here](https://nodejs.org/api/esm.html#resolvespecifier-context-nextresolve) is some sample code from the official nodejs docs. 
note that this pr doesn't include any tests if these a wanted/needed i would happy to provide them.

url now returns the href of a url object

---

packages/integrate-module/src/foo.mts
packages/integrate-module/src/index.ts
packages/integrate-module/src/subdirectory/bar.mts
packages/integrate-module/src/subdirectory/baz.mts
packages/integrate-module/src/subdirectory/index.mts
packages/register/esm.mts

The current `register/esm` does not resolve relative file path correctly.
For example, the following code and command doesn't run properly.
code
```js
// index.mts
import './foo.mjs'
foo()
```
command
`node --loader @swc-node/register/esm index.mts`
and the error
```
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/path/to/foo.mjs' imported from /path/to/index.mts.mjs
```
This PR fixes the problem.

fix(register): Fix to resolve adjacent file path

---

packages/core/index.ts
packages/jest/__test__/hoist-top-level.spec.ts
packages/register/__test__/ts-compiler-options-to-swc-config.spec.ts
packages/register/read-default-tsconfig.ts

fix: tsCompilerOptionsToSwcConfig should not override default swc config for jest

---

packages/register/esm.mts

currently when import with absolute path, error shows:
```
node:internal/errors:496
ErrorCaptureStackTrace(err);
^
TypeError [ERR_INVALID_URL]: Invalid URL
at new NodeError (node:internal/errors:405:5)
at new URL (node:internal/url:611:13)
at fileURLToPath (node:internal/url:1399:12)
at resolve (file:///xxx/node_modules/@swc-node/register/esm/esm.mjs:66:35)
at nextResolve (node:internal/modules/esm/loader:163:28)
at ESMLoader.resolve (node:internal/modules/esm/loader:835:30)
at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
at ESMLoader.import (node:internal/modules/esm/loader:524:22)
at importModuleDynamically (node:internal/modules/esm/translators:110:35)
at importModuleDynamicallyCallback (node:internal/process/esm_loader:35:14) {
input: '/Volumes/test/10_client.ts', …
```

fix: fix import absolute path support

---

packages/core/index.ts

#721 did declare `baseUrl` property, but did not assign that.
This PR fixes it to fix problems something like:
`failed to handle: base_dir() must be absolute. Please ensure that jsc.baseUrl is specified correctly.`

fix(core): assign `baseUrl` property

---

packages/core/index.ts
packages/register/register.ts

The current `@swc-node/register/esm` loader does not respect the `SWCRC` environment variable. This is due to the condition for setting `swcRegisterConfig` only applying to the sync `transform` version.
This PR fixes that, and also fixes `module` being overridden by `"commonjs"` when `SWCRC` environment variable is specified, which causes files being transformed by `register/esm` to be loaded as CommonJS which causes errors such as these:
```
server  | file:///app/apps/backend/src/app.ts:2
server  | Object.defineProperty(exports, "__esModule", {
server  |                       ^
server  |
server  | ReferenceError: exports is not defined in ES module scope
server  |     at file:///app/apps/backend/src/app.ts.mjs:2:23
server  |     at ModuleJob.run …
```

fix(register): respect SWCRC environment variable when running in async mode

---

packages/core/index.ts

Closes #732
Actually, this is just a bit of a json manipulation, so I thought someone would already have sent a PR, but it wasn't.

fix(core): remove `jsc.module.noInterop` when it's not supported

---

packages/register/esm.mts

Currently `@swc-node/register/esm` has its own implementation in `register` hook to resolve imports like `./foo` or `./foo.ts`. However, the resolution should be aligned with that by TypeScript (specifically `tsserver`) which is far more complicated.
This PR just uses TypeScript resolver in `register` hook. In this way, the resolution will respect setting files such as tsconfig.json, package.json, and so on. Thus, this PR potentially fixes issues #710 and #724, and adds support for `paths` in `tsconfig.json`.
As of the performance issue, it can be said that TypeScript resolver will not search deep into `node_modules`; if parentURL is in `node_modules` the resolver falls back to default one, and so does if the resolution result. Note that TypeScript resolver itself is already fast enough. …

feat(register): @swc-node/register/esm use TypeScript resolver

---

packages/core/index.ts

Fixes #741
When using a `.swcrc` file, the `sourceMaps` setting is ignored and always set as `"inline"` in the SWC config.
This PR fixes the issue by leaving `sourceMaps` undefined in the SWC config, so that the value from the `.swcrc` file takes effect.

fix(core): respect sourceMaps swcrc value

---

.gitignore
README.md
package.json
packages/register/esm-register.mts
packages/register/package.json
packages/register/tsconfig.esm.json
pnpm-lock.yaml

According to the node.js [release notes](https://nodejs.org/en/blog/release/v20.6.0) for node 20.6 the experimental loaders API was deprecated in favour of the register API.
Because of that, we need to use node --import register.js file.ts instead of node --loader @swc-node/register/esm file.ts.
close #743

feat: add esm-register for node>20.6

---

packages/core/index.ts
packages/register/read-default-tsconfig.ts

Add the `ignoreDynamic` option to the `@swc-node/core`, and the `SWC_NODE_IGNORE_DYNAMIC` env option.
----
Given the following the CLI written in TypeScript:
```ts
#!/usr/bin/env node
import { arg } from 'arg'
async function main() {
// some CLI stuff
// ...
arg();
const { method } = await import('some-pure-esm-module');
// other stuff
}
main().catch(exit)
```
SWC emits the following output when transpiling it into CommonJ,:
```js
#!/usr/bin/env node
"use strict";
Object.defineProperty(exports, "__esModule", {
value: true
});
const _arg = require("arg");
function _getRequireWildcardCache(nodeInterop) {
if (typeof WeakMap !== "function") return null;
var cacheBabelInterop = new WeakMap();
var cacheNodeInterop = new WeakMap();
return (_getRequireWildcardCache = function(nodeInterop) { …
```

feat(core): support swc's `ignoreDynamic` option

---

packages/register/esm.mts

as https://github.com/swc-project/swc-node/pull/727#pullrequestreview-1760882920 describes, when import `.ts` files from node_moduels, it throws error `TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts"`.
it works well in 1.6.7
example scene: monorepo import .ts file in project,  or server framework wants dynamic load routes in development

fix: fix import ts from node_modules

---

README.md

`@swc-node/sourcemap-support` only works on cjs projects. The underlying library `source-map-support` is more than 2 years old and doesn't seem to work with native esm.
Ask people to use Node's built-in source map support. Although experimental, it works well in my very minimal setup.
Related issue: https://github.com/swc-project/swc-node/issues/719

Mention --enable-source-maps in README.md for esm projects.

---

.changeset/spotty-mails-relate.md
package.json
packages/register/__test__/ts-compiler-options-to-swc-config.spec.ts
packages/register/esm.mts
packages/register/read-default-tsconfig.ts

this commit fix some esm module resolve bugs
1. convert fileUrl to path before compile in esm, which may cause path alias resolve issue to align with previous behavior. close #753
2. remove baseUrl from esm to keep module import specifier, as we use tsc resolver.

fix: esm module resolve issues

---

.changeset/three-rockets-jump.md
packages/register/read-default-tsconfig.ts

In previous pr #754, when `tsconfig.baseUrl` not set, it keeps undefined in swcConfig (to compatible with esm module resolver).
It is a breaking change, case after typescript@4.1 `baseUrl` is an optional value which defaults to dirname of `tsconfig.json`
This pr add a default value to `tsconfig.baseUrl` when `tsconfig.paths` not empty, fixed errors caused by empty `baseUrl` in `tsconfig.json`.

fix: add default tsconfig.baseUrl to align with tsc behavior

---

.changeset/great-goats-trade.md
packages/register/esm.mts

Third-party executors like mocha, may import scripts with fileUrl absolute path.
This pr converts `specifier` from fileUrl to path.
close #762

fix(register): fix esm entry resolver for third-party executer, close #762

---

.changeset/ninety-singers-roll.md
packages/integrate/__tests__/extention/extention.spec.ts
packages/integrate/package.json
packages/integrate/tsconfig.json
packages/register/register.ts
pnpm-lock.yaml

this issue fixes a bug caused by an invalid regexp, which provides a fast way to detect if the specific file is allowed to transform.
Texts for the case have been added as weel.
fix #775 
fix #774 
fix #772

fix: fix ts extension detect regex, close #775 #774 #772

---

packages/integrate-module/src/index.ts
packages/integrate-module/tsconfig.json
packages/register/esm.mts

This PR as a continuation of #727  and #767 
1. almost full rewrite the esm resolver, fallback to use node resolver if ts resolve unexpected. this supports js files with `d.ts` files the same time
2. trying to guess module format for absolute file import, supports absolute import like mocha
relate: #727 #754  #766 #767 #777
fix #779

feat: update esm module resolver

---

packages/register/esm.mts

Hello,
I encountered an issue with `@swc-node/register@1.9.2` that did not happen with version `1.9.1`
Pull requests with the issue:
- https://github.com/fargito/rust-cdk-serverless/pull/231
- https://github.com/fargito/event-scout/pull/386
Both projects are esm-only, with Node v20.14.0, running swc with `node --import @swc-node/register/esm-register my-entrypoint.ts`. Also they don't have extensions in the internal imports (i.e. `import  { foo } from './foo'` and not `import { foo } from './foo.js'`).
In #777 the pattern matching for supported extensions, was fixed. It used to match every single string.
However, now that this pattern is correct, the condition used to check it the specifier was supported was no longer valid for extension-less specifiers.
E.g.
```ts
import { foo } from …
```

fix(esm-resolver): only return early if the specifier is an unsupported file

---

packages/register/register.ts

feat(register): do not send undefined source code for compilation

---

packages/integrate-module/package.json
packages/integrate-module/src/component.tsx
packages/integrate-module/src/index.ts
packages/integrate-module/tsconfig.json
packages/register/esm.mts
pnpm-lock.yaml

- Close https://github.com/swc-project/swc-node/issues/799

fix(register): tsx file

---

packages/register/esm.mts

- Close https://github.com/swc-project/swc-node/issues/804
- Close https://github.com/swc-project/swc-node/issues/770

fix(register): support moduleResolution Bundler

---

package.json

`husky install` -> `husky` (same command)
https://github.com/typicode/husky/releases/tag/v9.0.1

chore: replace deprecated husky install

---

README.md

The previous hashbang did not work on Linux coreutils `env` because `env` passes the arguments as single string to `node`. By adding `-S` we can make it split the arguments and this works on both GNU coreutils >= 8.30 and BSD `env` (probably since 2005) used on MacOS.
Also see https://github.com/privatenumber/tsx/pull/523 and https://unix.stackexchange.com/a/477651.

docs: recommend `-S` on hashbang

---

packages/register/esm.mts

Thank you for the fix for #799. Unfortunately I still cannot directly run a .tsx file without the change in this PR. This change makes register/esm consider a .tsx file to be a module like .ts. Also a `.` was missing before `tsx` in an array.

fix(register): allow running .tsx file

---

packages/core/index.ts
packages/integrate-module/src/index.ts

- Close https://github.com/swc-project/swc-node/issues/815

fix(register): enable keepImportAttributes in SWC options

---

packages/register/esm.mts

TLDR: `node --import @swc-node/register/esm-register` ...` gives an error like:
```
Error: Tsconfig not found C:\some\package\path\C:\some\package\path\tsconfig.json: .....
```
Not sure why the current CI tests didn't catch this, I'm happy to try adding it if you could point me where such a test would belong?

fix(register): default register/esm TSCONFIG_PATH on windows.

---

packages/integrate-module/package.json
packages/integrate-module/src/index.ts
packages/register/esm.mts
pnpm-lock.yaml

- Close https://github.com/swc-project/swc-node/issues/827

fix(register): skip load files in node_modules

---

packages/register/esm.mts

compile() expects a filename, not a url: it passes the value directly to the bindings module, which immediately parses it as a `Path` unconditionally.
This causes input file source maps to fail to load, as it attempts to find the URL as if it were a file on disk. (see https://github.com/swc-project/swc/pull/9422)
This is a targeted fix which hopefully minimizes the chance of things breaking.

fix(register/esm): pass file urls as paths

---

packages/register/register.ts

We encountered an issue that requires us to specify a custom SWC configuration file when using the `swc-node/register ` package. Our project does not use TypeScript, and we wish to avoid placing irrelevant files like `tsconfig.json` in our root directory. Additionally, we are integrating Jest with `@swc/jest`, which leads to conflicts with the root `.swcrc` file.
To resolve this, we need the ability to specify a custom path for the `.swcrc` file and prevent the root `.swcrc` from being used during real-time node building. The SWC API allows for this through the`configFile` property, which can be implemented similarly to setting `SWCRC=true`.
Our migration process is currently hindered by this limitation, and we've had to temporarily override your package locally.

feat(CLI): Added possibility to have custom config location for swc

---

packages/register/read-default-tsconfig.ts

The PR adds the `SWC_NODE_INLINE_SOURCE_MAP` alongside the existing tscofig options. It is useful when the source map is needed with `@swc-node/register` w/o changing other bundlers/compilers/linters' behavior.
----
Currently, I have a `tsconfig.json` that, with source map disabled, is used to build the dist and run some maintenance scripts with `@swc-node/register`, and it works great.
However, to get the correct stacktrace and coverage report with `mocha` and `nyc`, I will need to enable sourcemap. Currently, it requires an extra `tsconfig` file **specifically** for `@swc-node/register` to enable source map for tests:
```jsonc
// tsconfig.test-swc.json
{
"extends": "./tsconfig.json",
"compilerOptions": {
"inlineSourceMap": true
}
}
```
```bash
SWC_NODE_IGNORE_DYNAMIC=1 …
```

feat(register): add new env `SWC_NODE_INLINE_SOURCE_MAP`
